extends Node3D

## Residential architecture gallery (mission "Godot tests"): one deterministic
## representative house per production style, laid out in a grid and screenshotted.
##
## Two modes prove the mission's central claim — that style changes GEOMETRY, not
## just colour:
##   --neutral : every surface forced to one flat grey material, so Craftsman /
##               Tudor / Ranch / MCM / Colonial must stay distinguishable from
##               SILHOUETTE alone (the important gate).
##   (default) : full WorldMaterials shader (brick courses, siding, tile, seams).
##
## The houses are the real Python-compiled ResidentialArchitectureV1 records from
## godot/tests/residential_gallery.json (generated by tools/gen_residential_gallery.py)
## rendered through the SAME ResidentialHouseRenderer the live world uses — the
## renderer never re-rolls anything.
##
##   godot --headless res://tests/ResidentialArchitectureGallery.tscn -- \
##       [--neutral] --out /tmp/res_gallery.png

const ResidentialHouseRenderer = preload("res://scripts/residential_house_renderer.gd")

var _out := "/tmp/res_gallery.png"
var _neutral := false


func _ready() -> void:
	var args := OS.get_cmdline_user_args()
	for i in range(args.size()):
		if args[i] == "--out" and i + 1 < args.size():
			_out = args[i + 1]
		elif args[i] == "--neutral":
			_neutral = true
	await _run()


func _load_houses() -> Array:
	var f := FileAccess.open("res://tests/residential_gallery.json", FileAccess.READ)
	if f == null:
		push_error("missing residential_gallery.json — run tools/gen_residential_gallery.py")
		return []
	var doc: Variant = JSON.parse_string(f.get_as_text())
	if typeof(doc) != TYPE_DICTIONARY:
		return []
	return doc.get("houses", [])


func _run() -> void:
	var env := Environment.new()
	env.background_mode = Environment.BG_COLOR
	env.background_color = Color(0.60, 0.64, 0.68) if not _neutral else Color(0.5, 0.5, 0.52)
	env.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	env.ambient_light_color = Color(0.78, 0.80, 0.84)
	env.ambient_light_energy = 0.85
	var we := WorldEnvironment.new()
	we.environment = env
	add_child(we)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-50, -44, 0)
	sun.light_energy = 1.15
	sun.shadow_enabled = true
	add_child(sun)

	var ground := MeshInstance3D.new()
	var pm := PlaneMesh.new()
	pm.size = Vector2(400, 400)
	ground.mesh = pm
	var gmat := StandardMaterial3D.new()
	gmat.albedo_color = Color(0.40, 0.44, 0.38) if not _neutral else Color(0.62, 0.62, 0.62)
	ground.material_override = gmat
	ground.position = Vector3(0, -0.02, 0)
	add_child(ground)

	var houses := _load_houses()
	# grid layout: 4 columns, cell 26 m so the widest ranch clears its neighbour.
	var cols := 4
	var cell := 26.0
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	var total_verts := 0
	var min_x := INF
	var max_x := -INF
	var min_z := INF
	var max_z := -INF
	for i in range(houses.size()):
		var h: Dictionary = houses[i]
		var gx := float(i % cols) * cell
		var gz := float(floori(float(i) / float(cols))) * cell
		var b := _translate(h, gx, gz)
		total_verts += ResidentialHouseRenderer.emit(st, b, PackedByteArray(), Vector2.ZERO)
		min_x = minf(min_x, gx - cell * 0.5)
		max_x = maxf(max_x, gx + cell * 0.5)
		min_z = minf(min_z, gz - cell * 0.5)
		max_z = maxf(max_z, gz + cell * 0.5)

	st.generate_normals()
	var mi := MeshInstance3D.new()
	mi.mesh = st.commit()
	if _neutral:
		# Flat grey: bypass the material-family shader so ONLY shape is visible.
		var nm := StandardMaterial3D.new()
		nm.albedo_color = Color(0.72, 0.72, 0.72)
		nm.vertex_color_use_as_albedo = false
		mi.material_override = nm
	else:
		mi.material_override = WorldMaterials.building_material()
	add_child(mi)

	# frame the grid with an iso ortho camera
	var w := max_x - min_x
	var d := max_z - min_z
	var center := Vector3((min_x + max_x) * 0.5, 2.0, (min_z + max_z) * 0.5)
	var cam := Camera3D.new()
	cam.projection = Camera3D.PROJECTION_ORTHOGONAL
	cam.size = 0.62 * (w + d) + 12.0
	cam.near = 0.1
	cam.far = 5000.0
	cam.position = center + Vector3(-0.55, 0.7, -0.55).normalized() * ((w + d) + 80.0)
	add_child(cam)
	cam.look_at(center, Vector3.UP)
	cam.make_current()

	for _i in range(8):
		await get_tree().process_frame
	await get_tree().create_timer(0.3).timeout
	var img := get_viewport().get_texture().get_image()
	img.save_png(_out)
	print("RES_GALLERY saved: %s (%d styles, %d verts, neutral=%s)"
		% [_out, houses.size(), total_verts, _neutral])
	get_tree().quit(0)


## Translate a house dict's footprint into its grid cell (keeps the compiled
## architecture record intact — only the polygon moves).
static func _translate(h: Dictionary, ox: float, oz: float) -> Dictionary:
	var b := h.duplicate(true)
	var poly: Array = b.get("poly", [])
	var moved: Array = []
	for p in poly:
		moved.append([float(p[0]) + ox, float(p[1]) + oz])
	b["poly"] = moved
	return b
