"""Canonical StreetMap + spawn anchors from a *compiled* world bundle.

For cities that carry `world/` data (the outside-world compiler output),
citizens are baked against the SAME building stock the game renders:
buildings.json regenerated by the compiler (index == authoritative
building_id) and the full road network. This retires the old
`street_map_from_bundle` blocks-scatter path for compiled cities — the
audited divergence where bundle-rebaked citizens lived in decorative
blocks rather than real buildings.

Spawn placement consumes the compiled spawn anchors (world/
spawn_anchors.json): entrances for home/work spawns, road/sidewalk
anchors for routed commute spawns.  The straight-line commute
approximation is retired here.
"""
from __future__ import annotations

import heapq
import json
import math
import os

from ..world import (
    CIVIC,
    COMMERCIAL,
    EDUCATION,
    INDUSTRIAL,
    MEDICAL,
    RESIDENTIAL,
    Building,
    StreetMap,
)
from .world_from_osm import _sector

# Building exterior archetype -> occupation workplace category.
ARCH_TO_CATEGORY = {
    "DETACHED_RESIDENTIAL": RESIDENTIAL,
    "MULTIFAMILY": RESIDENTIAL,
    "SMALL_COMMERCIAL": COMMERCIAL,
    "BIG_BOX_COMMERCIAL": COMMERCIAL,
    "OFFICE_HIGHRISE": COMMERCIAL,
    "INDUSTRIAL": INDUSTRIAL,
    "CIVIC_SPECIAL": CIVIC,
    "GENERIC_UNKNOWN": RESIDENTIAL,
}
# Parcel archetypes refine civic specials when present on the anchor table.
PARCEL_TO_CATEGORY = {
    "SCHOOL": EDUCATION,
    "MEDICAL": MEDICAL,
}


def has_compiled_world(bundle_dir: str) -> bool:
    return os.path.exists(os.path.join(bundle_dir, "world", "world_meta.json"))


def _polygon_area(ring) -> float:
    a = 0.0
    for i in range(len(ring)):
        x0, z0 = ring[i]
        x1, z1 = ring[(i + 1) % len(ring)]
        a += x0 * z1 - x1 * z0
    return abs(a) / 2.0


def street_map_from_compiled(bundle_dir: str) -> StreetMap:
    """Build the canonical StreetMap from compiled buildings + bundle roads."""
    with open(os.path.join(bundle_dir, "buildings.json")) as f:
        bjson = json.load(f)
    with open(os.path.join(bundle_dir, "roads.json")) as f:
        rjson = json.load(f)
    world_bounds = None
    meta_path = os.path.join(bundle_dir, "world", "world_meta.json")
    if os.path.exists(meta_path):
        with open(meta_path) as f:
            world_bounds = json.load(f).get("bounds_m")

    # Street graph from the bundle's (already metre-frame) polylines.
    nodes: dict[int, tuple[float, float]] = {}
    node_of: dict[tuple[int, int], int] = {}
    edges: list[tuple[int, int, float]] = []

    def node_id(x: float, z: float) -> int:
        key = (int(round(x)), int(round(z)))
        nid = node_of.get(key)
        if nid is None:
            nid = len(nodes)
            node_of[key] = nid
            nodes[nid] = (float(x), float(z))
        return nid

    for pl in rjson.get("polylines", []):
        prev = None
        for x, z in pl.get("points", []):
            nid = node_id(x, z)
            if prev is not None and prev != nid:
                a, b = nodes[prev], nodes[nid]
                length = math.hypot(a[0] - b[0], a[1] - b[1])
                if length > 0:
                    edges.append((prev, nid, length))
            prev = nid

    xs, zs = [], []
    tmp = []
    for entry in bjson.get("buildings", []):
        ring = [(float(p[0]), float(p[1])) for p in entry.get("poly", [])]
        if len(ring) < 3:
            tmp.append(None)  # keep index == building_id alignment
            continue
        area = _polygon_area(ring)
        cx = sum(p[0] for p in ring) / len(ring)
        cz = sum(p[1] for p in ring) / len(ring)
        if world_bounds is not None and not (
                world_bounds[0] <= cx <= world_bounds[2]
                and world_bounds[1] <= cz <= world_bounds[3]):
            # Edge-straddling buildings render, but citizens cannot live or
            # work somewhere the playable extent cannot host a spawn.
            tmp.append(None)
            continue
        h = float(entry.get("height", 3.3))
        cat = ARCH_TO_CATEGORY.get(entry.get("arch", ""), RESIDENTIAL)
        tmp.append((ring, area, (cx, cz), max(1, round(h / 3.3)), cat))
        xs += [p[0] for p in ring]
        zs += [p[1] for p in ring]

    bbox_m = (min(xs), min(zs), max(xs), max(zs)) if xs else (0.0, 0.0, 1.0, 1.0)
    if not nodes:
        nodes = {0: ((bbox_m[0] + bbox_m[2]) / 2.0, (bbox_m[1] + bbox_m[3]) / 2.0)}

    sm = StreetMap(nodes=nodes, edges=edges, buildings=[], bbox=bbox_m,
                   source=f"compiled:{os.path.basename(bundle_dir)}")
    built = []
    for i, item in enumerate(tmp):
        if item is None:
            continue
        ring, area, (cx, cz), levels, cat = item
        built.append(Building(
            id=i, category=cat, footprint=ring, centroid=(cx, cz),
            area=area, levels=levels,
            neighborhood=_sector(cx, cz, bbox_m),
            street_node=sm.nearest_node((cx, cz)),
            name=f"{_sector(cx, cz, bbox_m)} {cat} {i}",
        ))
    sm.buildings = built
    return sm


class SpawnAnchors:
    """Compiled spawn anchors + routed commute placement over the StreetMap."""

    def __init__(self, bundle_dir: str, street_map: StreetMap):
        import gzip
        path = os.path.join(bundle_dir, "world", "spawn_anchors.json.gz")
        with gzip.open(path, "rt", encoding="utf-8") as f:
            data = json.load(f)
        self.entrance_by_bid: dict[int, tuple[float, float]] = {}
        self.walk_anchors: list[tuple[float, float]] = []
        self.parking_by_near: list[tuple[float, float]] = []
        for kind, x, z, bid in data.get("anchors", []):
            if kind == "BUILDING_ENTRANCE" and bid >= 0:
                self.entrance_by_bid.setdefault(int(bid), (float(x), float(z)))
            elif kind in ("SIDEWALK_ANCHOR", "PEDESTRIAN_APPROACH"):
                self.walk_anchors.append((float(x), float(z)))
            elif kind == "PARKING_ANCHOR":
                self.parking_by_near.append((float(x), float(z)))
        self.sm = street_map
        self._adj: dict[int, list[tuple[int, float]]] | None = None

    # -- routing -----------------------------------------------------------
    def _adjacency(self):
        if self._adj is None:
            adj: dict[int, list[tuple[int, float]]] = {}
            for a, b, w in self.sm.edges:
                adj.setdefault(a, []).append((b, w))
                adj.setdefault(b, []).append((a, w))
            self._adj = adj
        return self._adj

    def route(self, start_xy, end_xy) -> list[tuple[float, float]]:
        """Shortest road-graph path between the nodes nearest two points."""
        s = self.sm.nearest_node(start_xy)
        t = self.sm.nearest_node(end_xy)
        if s is None or t is None:
            return [tuple(start_xy), tuple(end_xy)]
        adj = self._adjacency()
        dist = {s: 0.0}
        prev: dict[int, int] = {}
        pq = [(0.0, s)]
        while pq:
            d, u = heapq.heappop(pq)
            if u == t:
                break
            if d > dist.get(u, float("inf")):
                continue
            for v, w in adj.get(u, []):
                nd = d + w
                if nd < dist.get(v, float("inf")):
                    dist[v] = nd
                    prev[v] = u
                    heapq.heappush(pq, (nd, v))
        if t not in dist:
            return [tuple(start_xy), tuple(end_xy)]
        path = [t]
        while path[-1] != s:
            path.append(prev[path[-1]])
        path.reverse()
        return [self.sm.nodes[n] for n in path]

    def commute_point(self, home_xy, work_xy, frac: float):
        """Point at `frac` of the routed home->work trip (never straight-line
        through buildings unless the graph is degenerate)."""
        pts = self.route(home_xy, work_xy)
        total = sum(math.hypot(pts[i + 1][0] - pts[i][0],
                               pts[i + 1][1] - pts[i][1])
                    for i in range(len(pts) - 1))
        if total <= 0:
            return tuple(home_xy), True
        target = frac * total
        acc = 0.0
        for i in range(len(pts) - 1):
            seg = math.hypot(pts[i + 1][0] - pts[i][0],
                             pts[i + 1][1] - pts[i][1])
            if acc + seg >= target and seg > 0:
                t = (target - acc) / seg
                return ((pts[i][0] + (pts[i + 1][0] - pts[i][0]) * t,
                         pts[i][1] + (pts[i + 1][1] - pts[i][1]) * t), False)
            acc += seg
        return pts[-1], False

    def entrance(self, bid: int | None):
        if bid is None:
            return None
        return self.entrance_by_bid.get(int(bid))

    def nearest_walk_anchor(self, xy):
        best, bd = None, float("inf")
        for a in self.walk_anchors:
            d = (a[0] - xy[0]) ** 2 + (a[1] - xy[1]) ** 2
            if d < bd:
                bd, best = d, a
        return best
