# GENERATED by asphodel.physics.layers.emit_gdscript() — DO NOT EDIT.
# The authoritative collision matrix lives in Python (AS-PHYS-0).
extends Node

# Layer bit constants (Godot layer index = bit position + 1).
const WORLD_STATIC := 1  # index 1
const PLAYER := 2  # index 2
const NPC := 4  # index 3
const VEHICLE := 8  # index 4
const DYNAMIC_PROP := 16  # index 5
const TRIGGER := 32  # index 6
const NAV_QUERY := 64  # index 7
const DAMAGE_QUERY := 128  # index 8

# Per-body-type {layer, mask} the engine assigns on spawn.
const PROFILES := {
	"damage_query": {"layer": 128, "mask": 15, "role": "query"},
	"dynamic_prop": {"layer": 16, "mask": 31, "role": "rigid_body"},
	"nav_query": {"layer": 64, "mask": 25, "role": "query"},
	"npc": {"layer": 4, "mask": 31, "role": "character_body"},
	"player": {"layer": 2, "mask": 31, "role": "character_body"},
	"trigger": {"layer": 32, "mask": 14, "role": "area"},
	"vehicle": {"layer": 8, "mask": 31, "role": "rigid_body"},
	"world_static": {"layer": 1, "mask": 0, "role": "static_body"},
}

func layer_of(kind: String) -> int:
	return PROFILES.get(kind, {}).get("layer", 0)

func mask_of(kind: String) -> int:
	return PROFILES.get(kind, {}).get("mask", 0)

