"""
Signature scenarios: the one situation each occupation makes *naturally* its own.

The premise is that being randomly spawned into a job isn't just a label and an
inventory -- it drops you into a specific predicament when the world ends.  A
nurse is on the ward as the casualties flood in; a train conductor is doing 90
between stations; a window washer is stranded in a cradle thirty storeys up; a
preschool teacher has a dozen toddlers and no parents answering.  Any job *could*
end up anywhere, but the signature is the experience that job tends to author.

Each occupation owns one ``SignatureScenario`` (data).  It fires through the
schedule: when the collapse lands while the citizen is *on shift* (or, for
home-anchored roles, any time), the resolver in ``citizen.py`` binds the
signature to the citizen's concrete location and on-hand assets.  Off-shift, the
signature doesn't fire -- a nurse asleep at home has her job's edge back at the
hospital, not with her -- which is itself an emergent, schedule-driven outcome.

This module is pure content: a dataclass plus the catalogue.  It imports nothing
from the rest of the package, so ``citizen.py`` can attach these to occupations
and resolve them without a cycle.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class SignatureScenario:
    """The defining collapse-moment predicament for one occupation."""

    name: str                       # short title
    trigger: str = "on_shift"       # "on_shift" | "on_site" | "anytime"
    location: str = ""              # evocative place the signature happens
    situation: str = ""             # what's unfolding when collapse hits
    dilemma: str = ""               # the choice it forces on the player
    assets: list[str] = field(default_factory=list)   # what the job gives you now
    hazards: list[str] = field(default_factory=list)  # what's working against you
    tags: list[str] = field(default_factory=list)     # mechanical hooks


def default_signatures() -> dict[str, SignatureScenario]:
    """The signature scenario for every occupation, keyed by occupation name.

    ``tags`` are the reusable mechanical hooks a game layer can switch on:
    height, trapped, vehicle_moving, mass_casualty, crowd, children, vulnerable,
    keys_access, tools, supplies, food, fuel, weapons, hazmat, infrastructure,
    information, isolation, mobility, animals.
    """
    S = SignatureScenario
    return {
        # --- home-anchored (fire any time) ---------------------------------
        "child": S("Too small to understand", "anytime",
                   "at home or the school playground",
                   "The grown-ups are screaming and no one will explain why.",
                   "Find a familiar adult, or hide where no one thinks to look.",
                   ["small enough to hide anywhere", "knows every shortcut nearby"],
                   ["dependent on adults", "easily overwhelmed"],
                   ["vulnerable", "mobility"]),
        "retiree": S("Forty years on this street", "anytime",
                     "at home or out on a morning walk",
                     "The street you've known for decades turns strange in minutes.",
                     "Stay put among neighbours, or accept a stranger's offer to leave.",
                     ["a paid-off, well-stocked home", "decades of local knowledge"],
                     ["slower on your feet", "dependent on medication"],
                     ["supplies", "vulnerable"]),
        "unemployed": S("No shift to miss", "anytime",
                        "at home or out on errands",
                        "There's no workplace expecting you -- you're just here when it breaks.",
                        "Move early and light, before the roads choke.",
                        ["nothing tying you to a schedule", "street-smart"],
                        ["few resources to fall back on"],
                        ["mobility"]),
        "homemaker": S("The house is yours", "anytime",
                       "at home, mid-chore",
                       "The home is yours and you know exactly what's in every cupboard.",
                       "Fortify a familiar, stocked house, or gather the household and run.",
                       ["a known, fully-stocked home", "trusted by the neighbours"],
                       ["tied to dependents"],
                       ["supplies", "children"]),

        # --- medical --------------------------------------------------------
        "nurse": S("The doors won't stop opening", "on_shift",
                   "the hospital floor at shift change",
                   "The waiting room is already three deep and the ambulances keep coming.",
                   "Triage who you can still save, or walk out while you can.",
                   ["medical supplies to hand", "knows where the drugs are kept"],
                   ["mass casualties", "first in line to be exposed"],
                   ["mass_casualty", "medical_supplies"]),
        "doctor": S("Every monitor alarming at once", "on_shift",
                    "a ward or clinic",
                    "All the alarms go off together and the staff are thinning out.",
                    "Hold the ward together, or grab a kit and go.",
                    ["clinical authority", "keys to the drug cabinet"],
                    ["overwhelmed by patients"],
                    ["mass_casualty", "medical_supplies", "keys_access"]),
        "paramedic": S("Driving toward the screaming", "on_shift",
                       "out on a callout in the ambulance",
                       "The radio dissolves into overlapping mayday calls.",
                       "Keep answering calls into the chaos, or take the rig somewhere safe.",
                       ["a fast emergency vehicle", "a trauma kit", "lights to part traffic"],
                       ["always sent toward the danger"],
                       ["vehicle_moving", "medical_supplies", "mobility"]),
        "pharmacist": S("A queue that won't take no", "on_shift",
                        "behind the pharmacy counter",
                        "A crowd forms that won't accept 'no prescription'.",
                        "Guard a counter full of medicine, or pocket what matters and slip out back.",
                        ["controlled drugs", "real medical knowledge", "a lockable counter"],
                        ["everyone wants what you're standing on"],
                        ["medical_supplies", "keys_access", "crowd"]),
        "care_worker": S("They can't be moved", "on_shift",
                         "a care home or a client's house",
                         "The residents can't move quickly and no relief is coming.",
                         "Stay with people who can't flee, or save yourself.",
                         ["the trust of vulnerable people", "meds and supplies on your round"],
                         ["responsible for the immobile"],
                         ["vulnerable", "medical_supplies"]),
        "lab_technician": S("Containment lockdown", "on_shift",
                            "a sealed laboratory",
                            "Containment alarms trip and the building locks down around you.",
                            "Trust the seals and shelter, or break out before the locks engage.",
                            ["a sealed, stocked building", "hazmat gear", "knows what's in the freezers"],
                            ["maybe the safest place, maybe the worst"],
                            ["isolation", "hazmat", "infrastructure"]),

        # --- education ------------------------------------------------------
        "student": S("Mid-lecture, all phones at once", "on_shift",
                     "a packed lecture hall",
                     "The lecture cuts off as every phone in the hall lights up.",
                     "Shelter on a campus you know, or join the rush for the doors.",
                     ["knows the campus layout", "a crowd of peers"],
                     ["a crush forming at the exits"],
                     ["crowd", "information"]),
        "teacher": S("Thirty kids look to you", "on_shift",
                     "a classroom of thirty",
                     "The intercom dies mid-announcement and thirty children turn to you.",
                     "Keep them calm and contained, or release them to parents who may never come.",
                     ["authority over a room", "the register of every child"],
                     ["responsible for minors", "panicking parents at the gate"],
                     ["children", "crowd"]),
        "professor": S("The hall stops listening to you", "on_shift",
                       "a lecture theatre",
                       "Mid-lecture, the theatre's phones buzz as one.",
                       "Marshal a hall of students, or retreat to a quiet office.",
                       ["knows every building on campus", "a room that defers to you"],
                       ["a crowd wanting answers you don't have"],
                       ["crowd", "information"]),
        "childcare_worker": S("Naptime, no parents answering", "on_shift",
                              "a preschool room of toddlers",
                              "It's naptime and suddenly no parent is picking up.",
                              "Keep a dozen tiny children together through the end of the world, or wait for guardians who may not come.",
                              ["a room built to keep children safe", "snacks, cots, supplies"],
                              ["a dozen helpless toddlers", "impossible to move fast"],
                              ["children", "vulnerable", "supplies"]),

        # --- civic / public service ----------------------------------------
        "police_officer": S("Dispatch goes silent", "on_shift",
                            "on night patrol",
                            "Dispatch falls quiet between bursts of coded calls.",
                            "Enforce an order that no longer exists, or shed the uniform.",
                            ["a sidearm and radio", "a marked vehicle", "lawful access"],
                            ["a target for the desperate"],
                            ["weapons", "vehicle_moving", "keys_access"]),
        "firefighter": S("Three fires, no water", "on_shift",
                         "the station or a callout",
                         "Three structure fires reported and no water pressure left.",
                         "Run toward the smoke, or save your crew.",
                         ["breathing gear", "cutting tools", "a fire engine"],
                         ["called into burning buildings"],
                         ["tools", "vehicle_moving", "supplies"]),
        "soldier": S("The chain of command fractures", "on_shift",
                     "on base or on duty",
                     "Orders over the radio start contradicting each other.",
                     "Hold the post, or take your training and gear into the open.",
                     ["weapons and training", "body armour", "unit cohesion, for now"],
                     ["orders that may be suicidal"],
                     ["weapons", "supplies"]),
        "corrections_officer": S("Some doors open, some don't", "on_shift",
                                 "the cell block of a jail",
                                 "Lockdown protocols fail halfway; some cells unlock, some stay sealed.",
                                 "Free people who might help or harm, or leave them locked as the world ends.",
                                 ["keys and control of the block", "restraints and weapons", "a hardened building"],
                                 ["a block full of desperate prisoners", "an impossible moral call"],
                                 ["keys_access", "weapons", "crowd", "trapped"]),
        "sanitation_worker": S("The only thing still moving", "on_shift",
                               "the streets, mid-collection round",
                               "Your truck is the only thing moving on a street already snarling up.",
                               "Abandon the round, or use a heavy truck to shove through.",
                               ["a heavy truck that clears obstacles", "knows every back alley"],
                               ["a slow, conspicuous vehicle"],
                               ["vehicle_moving", "mobility"]),
        "social_worker": S("In a stranger's living room", "on_shift",
                           "out on home visits",
                           "You're in someone else's living room when the sirens start.",
                           "Help the household you're with, or leave to reach your own.",
                           ["trusted access to homes", "a list of who's vulnerable where"],
                           ["far from your own people"],
                           ["information", "mobility"]),
        "lawyer": S("Court adjourns into chaos", "on_shift",
                    "a courthouse or office",
                    "Proceedings dissolve and the building empties around you.",
                    "Hold a secure building of records and people, or take the road.",
                    ["a defensible building", "persuasion", "knows who holds the power"],
                    ["soft skills, no hard ones"],
                    ["information", "keys_access"]),

        # --- commercial / services -----------------------------------------
        "office_worker": S("The lifts just stopped", "on_shift",
                           "a high floor of an office tower",
                           "The lifts die and the stairwell fills with everyone from above.",
                           "Descend with the crush, or wait it out at altitude.",
                           ["a defensible floor", "a kitchen and vending machines"],
                           ["trapped above ground", "no useful tools"],
                           ["height", "trapped", "crowd"]),
        "grocery_clerk": S("They've stopped paying", "on_shift",
                           "the shop floor of a supermarket",
                           "The store fills with people who are no longer queuing to pay.",
                           "Defend the stockroom, or melt into the crowd with a full cart.",
                           ["a building full of food and water", "keys to the stockroom"],
                           ["a mob wants what you're standing on"],
                           ["food", "supplies", "keys_access", "crowd"]),
        "chef": S("Front of house empties, gas still on", "on_shift",
                  "a restaurant kitchen",
                  "The dining room bolts and the burners are still lit.",
                  "Barricade a kitchen stocked for a week, or take the knives and leave.",
                  ["a walk-in full of food", "knives", "gas and running water"],
                  ["fire risk", "a glass-fronted ground floor"],
                  ["food", "tools", "supplies"]),
        "waiter": S("The dinner rush bolts", "on_shift",
                    "a busy restaurant floor",
                    "Mid-service the whole room stands up and leaves.",
                    "Loot the kitchen and stay, or vanish in the exodus.",
                    ["a building full of food", "knows every back exit"],
                    ["glass-fronted, ground floor"],
                    ["food", "supplies"]),
        "barista": S("Cups still steaming", "on_shift",
                     "a café",
                     "The morning queue scatters, drinks abandoned on the counter.",
                     "Hold a small stocked café, or grab supplies and walk.",
                     ["food and water", "a small lockable space"],
                     ["minimal defences"],
                     ["food", "supplies"]),
        "accountant": S("The spreadsheets freeze", "on_shift",
                        "an office",
                        "The screens lock up and the floor empties around your desk.",
                        "Wait it out in a safe building, or commit to the roads.",
                        ["a quiet, defensible floor"],
                        ["no practical skills for this", "stranded in an office park"],
                        ["trapped"]),
        "it_support": S("Everything falls over at once", "on_shift",
                        "a server room",
                        "Every system you maintain crashes together -- then the lights go.",
                        "Keep comms alive a little longer, or pull the plug and run.",
                        ["server-room UPS power", "knows the building's systems", "comms gear"],
                        ["chained to failing infrastructure"],
                        ["infrastructure", "information"]),
        "security_guard": S("You hold the keys", "on_shift",
                            "a locked commercial building",
                            "Your cameras show the streets turning while your doors are already locked.",
                            "Hold a building you control, or open it to the crowd outside.",
                            ["keys to everything", "CCTV over the area", "a lockable fortress"],
                            ["crowds will want in"],
                            ["keys_access", "information", "crowd"]),
        "cleaner": S("Alone with a master key", "on_shift",
                     "an empty office building at night",
                     "Emergency lights snap on while you're alone with the master key.",
                     "A whole empty building to yourself, or get out before others arrive.",
                     ["a master key to every floor", "an empty, stocked building", "the quiet corners"],
                     ["alone if it goes wrong"],
                     ["keys_access", "isolation", "supplies"]),
        "window_washer": S("Stranded on the sky-lift", "on_shift",
                           "a cradle on the side of a glass tower, thirty storeys up",
                           "The building's power stutters and the platform lurches to a dead halt.",
                           "Climb in through a window into a tower of strangers, or trust a dead winch.",
                           ["a high vantage over the whole district", "rope, harness and tools"],
                           ["stranded at lethal height", "at the mercy of the building's power"],
                           ["height", "trapped", "information"]),

        # --- industrial / trades -------------------------------------------
        "dock_worker": S("Cranes hang mid-lift", "on_shift",
                         "the container port",
                         "Klaxons, then nothing -- the cranes freeze mid-lift.",
                         "Hole up in a maze of containers, or take a vehicle off the docks.",
                         ["forklifts and cranes", "a maze of steel containers", "heavy tools"],
                         ["dead machinery", "exposed waterfront"],
                         ["tools", "supplies", "isolation"]),
        "factory_worker": S("The line jams", "on_shift",
                            "the production floor",
                            "The line seizes; the lights flicker and catch on backup power.",
                            "Shelter behind locked roller doors, or get out before the backup fails.",
                            ["heavy machinery", "a building on backup power", "tools"],
                            ["dangerous equipment caught mid-cycle"],
                            ["tools", "infrastructure"]),
        "construction_worker": S("A site full of tools", "on_shift",
                                 "a half-built structure",
                                 "The site radio dies and the tower crane sways empty overhead.",
                                 "Fortify a site full of materials, or load the tools and roll out.",
                                 ["power tools and generators", "raw materials to barricade", "a site truck"],
                                 ["an unfinished, unstable structure"],
                                 ["tools", "supplies", "vehicle_moving"]),
        "warehouse_worker": S("Pallets of everything", "on_shift",
                              "a distribution warehouse",
                              "The conveyors stop with pallets of everything sitting ready.",
                              "Barricade a warehouse of goods, or load a pallet onto a truck.",
                              ["aisles of supplies", "forklifts", "loading-dock vehicles"],
                              ["a prize others will come for"],
                              ["supplies", "tools", "vehicle_moving"]),
        "electrician": S("Hands in the panel as the grid dies", "on_shift",
                         "wiring a building or substation",
                         "The grid browns out while your hands are still in the panel.",
                         "You read the dying grid better than anyone -- use it or flee it.",
                         ["tools", "understands the power network", "a work van"],
                         ["live, failing electrics"],
                         ["tools", "infrastructure", "vehicle_moving"]),
        "plumber": S("You can still find water", "on_shift",
                     "under a sink or in a basement",
                     "Water hammers through the pipes as the mains begin to fail.",
                     "You can find water when no one else can -- stay useful, or go.",
                     ["tools", "knows where water flows", "a stocked van"],
                     ["stuck in someone else's basement"],
                     ["tools", "infrastructure", "vehicle_moving"]),
        "mechanic": S("A garage full of working cars", "on_shift",
                      "a garage full of vehicles",
                      "The forecourt empties; a dozen cars sit with keys in the office.",
                      "A garage of working vehicles and tools -- take your pick.",
                      ["vehicles to choose from", "tools and fuel", "can fix what breaks"],
                      ["a target for anyone wanting wheels"],
                      ["vehicle_moving", "tools", "fuel"]),
        "welder": S("Seal yourself in steel", "on_shift",
                    "a fabrication shop",
                    "The sparks die as power cuts to the shop.",
                    "Weld yourself in behind steel, or carry a cutting torch out.",
                    ["a cutting torch", "steel to barricade with", "heavy tools"],
                    ["fire and gas hazards"],
                    ["tools", "supplies"]),

        # --- driving / logistics -------------------------------------------
        "bus_driver": S("A rolling shelter full of strangers", "on_shift",
                        "behind the wheel of a full bus",
                        "Half your passengers want out; half want you to drive faster.",
                        "Empty the bus, or keep a rolling shelter moving.",
                        ["a large vehicle full of people", "a route memorised", "fare cash"],
                        ["responsible for a busload", "gridlock ahead"],
                        ["vehicle_moving", "crowd", "mobility"]),
        "taxi_driver": S("A fare screaming to drive", "on_shift",
                         "in the cab with a fare aboard",
                         "Your passenger is screaming at you to drive as the streets seize.",
                         "Keep driving for strangers, or take the cab and disappear.",
                         ["a car and the fastest routes", "cash", "local knowledge"],
                         ["a panicking passenger", "gridlock"],
                         ["vehicle_moving", "mobility"]),
        "delivery_driver": S("A van full of unknowns", "on_shift",
                             "mid-route in a loaded van",
                             "Your van is full of other people's parcels on a street going still.",
                             "A van of unknown supplies and a head full of back roads -- use them.",
                             ["a van full of goods", "knows every shortcut", "a vehicle"],
                             ["no idea what's in the boxes"],
                             ["vehicle_moving", "supplies", "mobility"]),
        "truck_driver": S("Forty tonnes in motion", "on_shift",
                          "on the highway with a full trailer",
                          "You're doing motorway speed with a full trailer when the radio fills with panic.",
                          "Press on in a rolling fortress, or abandon the rig for something nimble.",
                          ["a huge, hard-to-stop vehicle", "a trailer that might hold anything", "fuel and a sleeper cab"],
                          ["can't manoeuvre in tight streets"],
                          ["vehicle_moving", "supplies", "fuel"]),
        "courier": S("Faster than the panic", "on_shift",
                     "weaving through traffic on a bike",
                     "You're the only thing moving faster than the panic itself.",
                     "Outrun the gridlock everyone else is trapped in.",
                     ["a bike that ignores traffic", "knows every alley", "light and fast"],
                     ["exposed, carries little"],
                     ["mobility", "vehicle_moving"]),
        "postal_worker": S("You know which houses are empty", "on_shift",
                           "mid-round in a residential street",
                           "Halfway down a street of identical doors when it hits.",
                           "You know which houses are empty -- pick one and shelter.",
                           ["knows which homes are vacant", "a van", "access to yards and letterboxes"],
                           ["out in the open on foot"],
                           ["information", "mobility", "supplies"]),
        "train_conductor": S("Ninety miles an hour between stations", "on_shift",
                             "aboard a moving commuter train",
                             "The train is doing 90 between stations when every passenger's phone screams at once.",
                             "Stop in open country, or push on to a station packed with the panicking.",
                             ["a sealed, moving shelter", "authority over the carriages", "knows the line and the depots"],
                             ["a train full of people you're responsible for", "can only stop on the rails"],
                             ["vehicle_moving", "crowd", "trapped"]),

        # --- grounds / roaming ---------------------------------------------
        "landscaper": S("Three lawns from the truck", "on_shift",
                        "mowing a garden in a residential neighbourhood",
                        "You're three lawns from your truck when the street erupts.",
                        "Every house around you is a possible shelter -- pick the right door.",
                        ["roams homes across the whole city", "a truck of fuel and bladed tools", "reads which houses are empty"],
                        ["caught out in the open, on foot"],
                        ["mobility", "tools", "information", "supplies"]),
    }
